# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - src: 'https://github.com/ansibleguy/infra_ufw.git'
    version: 'stable'
    name: 'ansibleguy.infra_ufw'

  - src: 'https://github.com/ansibleguy/linux_users.git'
    version: 'stable'
    name: 'ansibleguy.linux_users'

  - src: 'https://github.com/ansibleguy/linux_networking.git'
    version: 'stable'
    name: 'ansibleguy.linux_networking'

collections:
  - name: 'community.general'
    source: 'https://galaxy.ansible.com'

  - name: 'ansible.posix'
    source: 'https://galaxy.ansible.com'
