# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - src: 'https://github.com/ansibleguy/base-ufw.git'
    version: 'stable'
    name: 'ansibleguy.base-ufw'
  - src: 'https://github.com/ansibleguy/base-user.git'
    version: 'stable'
    name: 'ansibleguy.base-user'
  - src: 'https://github.com/ansibleguy/base-network.git'
    version: 'stable'
    name: 'ansibleguy.base-network'
  - src: 'https://github.com/ansibleguy/base-user.git'
    version: 'stable'
    name: 'ansibleguy.base-user'
