---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - src: 'ansibleguy.linux_ufw'
  - src: 'ansibleguy.linux_users'
  - src: 'ansibleguy.linux_networking'

collections:
  - name: 'community.general'
  - name: 'ansible.posix'
