---

- name: Bootstrap | Debian | Install base packages
  ansible.builtin.apt:
    name: "{{ base_packages.debian[ansible_distribution_major_version] | default(base_packages.debian.other) }}"
    state: present

- name: Bootstrap | Debian | Install tools
  ansible.builtin.apt:
    name: "{{ install_tools_list.debian[ansible_distribution_major_version] | default(install_tools_list.debian.other) }}"
    state: present
  when: install_tools

- name: Bootstrap | Debian | Install guest tools
  ansible.builtin.apt:
    name: "{{ vm_packages.debian[ansible_distribution_major_version] | default(vm_packages.debian.other) }}"
    state: present
  when:
    - ansible_virtualization_role is defined
    - ansible_virtualization_role == 'guest'

- name: Bootstrap | Debian | Default config
  ansible.builtin.import_tasks: debian/config.yml

- name: Bootstrap | Debian | AutoUpdate config
  ansible.builtin.import_tasks: debian/update.yml
  when: configure_auto_update

- name: Bootstrap | Debian | Configure ssh
  ansible.builtin.import_tasks: debian/ssh.yml
  when: configure_ssh

- name: Bootstrap | Debian | Configuring firewall
  ansible.builtin.include_role:
    name: ansibleguy.base-ufw
  when:
    - configure_firewall
    - ufw_rules is defined
    - ufw_rules | length > 0
