---

- name: Bootstrap | Base config
  ansible.builtin.import_tasks: base.yml
  tags: [base]
  when: >
    part is undefined or
    part|int == 1

- name: Bootstrap | Processing users
  ansible.builtin.include_role:
    name: ansibleguy.linux_users
  when: >
    (part is undefined or
    part|int == 1)
    and
    (BOOTSTRAP.configure_users and
    ((system_auth.users is defined and system_auth.users | length > 0) or
    (system_auth.groups is defined and system_auth.groups | length > 0)))
  tags: [users, groups, auth]

- name: Bootstrap | Processing debian post-user config
  ansible.builtin.import_tasks: debian/post_user.yml
  tags: [base]
  when: ansible_distribution|lower in ['debian', 'ubuntu']

- name: Bootstrap | Processing network
  ansible.builtin.include_role:
    name: ansibleguy.linux_networking
  when: >
    (part is undefined or
    part|int == 2)
    and
    BOOTSTRAP.configure_network and
    network is defined
  tags: [interfaces, routing]
