---

# todo: totp authentication

- name: Bootstrap | SSH | Lockout check
  ansible.builtin.pause:
    prompt: "You are about to deny root ssh-access without deploying users!
    This could lead to you locking yourself out!
    Do you want to continue? (YES/no)"
  register: ssh_lockout_check
  when:
    - not ssh_config.allow_root | default(default_ssh_config.allow_root)
    - not configure_users or users is not defined or users|length == 0

- name: Bootstrap | SSH | Deploying ssh config
  ansible.builtin.template:
    src: 'templates/etc/ssh/sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
    owner: 'root'
    group: 'root'
    mode: 0644
    backup: "{{ backup_config }}"
  notify: 'restart_sshd'
  when: >
    ssh_lockout_check.user_input is undefined or
    ssh_lockout_check.user_input in ['y', 'yes', 'Y', 'YES']

- name: Bootstrap | SSH | Deploying ssh pre-login banner
  ansible.builtin.copy:
    content: |
      {% for line in  ssh_config.banner_msg | default(default_ssh_config.banner_msg) %}
      {{ line }}
      {% endfor %}
    dest: '/etc/ssh/banner.txt'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'restart_sshd'
  when: ssh_config.msg | default(default_ssh_config.msg)

- name: Bootstrap | SSH | Deploying ssh post-login banner
  ansible.builtin.copy:
    content: |
      {% for line in  ssh_config.welcome_msg | default(default_ssh_config.welcome_msg) %}
      {{ line }}
      {% endfor %}
    dest: '/etc/motd'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: 'restart_sshd'
  when: ssh_config.msg | default(default_ssh_config.msg)
