---

# todo: move auto-update to own repository and add pip-autoupgrade (multi-venv) option

- name: Bootstrap | AutoUpdate | Install update tool
  ansible.builtin.apt:
    name: "{{ BOOTY_HC.update_packages }}"
    state: present

- name: Bootstrap | AutoUpdate | Setting update time (1/2)
  ansible.builtin.file:
    path: "{{ item }}"
    owner: 'root'
    group: 'root'
    state: directory
    mode: 0755
  loop:
    - '/etc/systemd/system/apt-daily.timer.d'
    - '/etc/systemd/system/apt-daily-upgrade.timer.d'

- name: Bootstrap | AutoUpdate | Setting update time (2/2)
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.timer.d/override.conf.j2"
    dest: "/etc/systemd/system/{{ item }}.timer.d/override.conf"
    owner: 'root'
    group: 'root'
    mode: 0640
  loop:
    - 'apt-daily'
    - 'apt-daily-upgrade'

- name: Bootstrap | AutoUpdate | Configuring update settings
  ansible.builtin.template:
    src: 'templates/etc/apt/apt.conf.d/50unattended-upgrades.j2'
    dest: '/etc/apt/apt.conf.d/50unattended-upgrades'
    owner: 'root'
    group: 'root'
    mode: 0640
  register: update_config

- name: Bootstrap | AutoUpdate | Enabling unattended-upgrades
  ansible.builtin.command:
    cmd: 'debconf-set-selections'
    stdin: 'unattended-upgrades unattended-upgrades/enable_auto_updates boolean true'
  changed_when: false

- name: Bootstrap | AutoUpdate | Reconfiguring unattended-upgrades
  ansible.builtin.command: 'dpkg-reconfigure -f noninteractive unattended-upgrades'
  changed_when: false
  when: update_config.changed

- name: Bootstrap | AutoUpdate | Starting / Enabling update services
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: restarted
    enabled: yes
  changed_when: false
  loop:
    - 'apt-daily-upgrade.timer'
    - 'apt-daily.timer'
