---

- name: Bootstrap | Debian | AutoUpdate | Install update tool
  ansible.builtin.apt:
    name: ['unattended-upgrades']
    state: present

- name: Bootstrap | Debian | AutoUpdate | Setting update time (1/2)
  ansible.builtin.file:
    path: '/etc/systemd/system/apt-daily.timer.d'
    owner: 'root'
    group: 'root'
    state: directory
    mode: 0755

- name: Bootstrap | Debian | AutoUpdate | Setting update time (2/2)
  ansible.builtin.template:
    src: 'templates/etc/systemd/system/apt-daily.timer.d/override.conf.j2'
    dest: '/etc/systemd/system/apt-daily.timer.d/override.conf'

- name: Bootstrap | Debian | AutoUpdate | Configuring update settings
  ansible.builtin.template:
    src: 'templates/etc/apt/apt.conf.d/50unattended-upgrades.j2'
    dest: '/etc/apt/apt.conf.d/50unattended-upgrades'

- name: Bootstrap | Debian | AutoUpdate | Enabling update services
  ansible.builtin.systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - 'apt-daily-upgrade.timer'
    - 'apt-daily.timer'
